extends Node

enum Item {NATURE, MOBILITY, ENERGY_BUILDING, COMMUNITY, CIRCULAR_ECONOMY, LOCAL_CONSUMPTION, NONE}

enum Achievements {CLIMATE_PROTECTION, HEALTHY_CITY, GREEN_CITY, SOCIAL_INTEGRATION, SHORT_WAYS, CIRCULAR_PRODUCE, FAIRTRADE_CITY}

const PLAYER_COUNT : int = 3
const MAX_AMOUNT_OF_ONE_ITEM : int = 100
